Fix accessing contentDocument on unbind when it is null
KyleAMathews/element-resize-event pull request #33
Opened 2018-09-18 12:42 UTC by tirli

Fixes #13 
Please merge and publish to NPM as this bug blocks not only me (according to issue)

2018-09-19 06:15 UTC, eaglus requested changes

2018-09-19 06:15 UTC, eaglus commented on index.js
> +      if (element.__resizeTrigger__.contentDocument && element.__resizeTrigger__.contentDocument.defaultView) {
Please, move element.__resizeTrigger__.contentDocument to variable for better readability, and i will merge it.

2018-09-19 06:15 UTC, eaglus commented on index.js
> +      if (element.__resizeTrigger__.contentDocument && element.__resizeTrigger__.contentDocument.defaultView) {
```
 var contentDocument = element.__resizeTrigger__.contentDocument;
 var defaultView = contentDocument && contentDocument.defaultView;
 if (defaultView) {
   defaultView.removeEventListener('resize', resizeListener);
   delete defaultView.__resizeTrigger__;
 }
```

2018-09-19 09:59 UTC, tirli commented
@eaglus updated

2018-09-19 14:26 UTC, merged

2018-09-20 08:13 UTC, tirli commented
@eaglus Thank you but seems like it's still not published. Can you do it or only @KyleAMathews have an access?

2018-09-20 09:23 UTC, eaglus commented
> @eaglus Thank you but seems like it's still not published. Can you do it or only @KyleAMathews have an access?

Hi Tirli! I can't publish this. I wrote email to KyleAMathews, to give me right for publishing, now i'm waiting for response